DROP TABLE IF EXISTS tbl_criterios_evaluacion;

CREATE TABLE tbl_criterios_evaluacion (
  id int(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  sigla varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci NOT NULL,
  criterio_evaluacion varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci NOT NULL UNIQUE,
  escala_valoracion_institucional varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci NOT NULL,
  descripcion_valoracion_institucional varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci NOT NULL,
  valor_hasta float NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;

INSERT INTO tbl_criterios_evaluacion (sigla,  criterio_evaluacion, escala_valoracion_institucional, descripcion_valoracion_institucional, valor_hasta) VALUES 
('BJ', 'DESEMPEÑO BAJO: NO CUMPLE CON LA EXPECTATIVAS DEL PROCESO DE ENSEÑANZA APRENDIZAJE, NO DEMUESTRA CONOCIMIENTO, DENOTA FALTA DE INTERÉS, NO PROPONE, Y NO HACE USO DE LOS RECURSOS REQUIERE ACCIONES PREVENTIVAS Y CORRECTIVAS.', 'EN PROCESO', ' NO ALCANZA LOS LOGROS MÍNIMOS Y REQUIERE ACTIVIDADES DE REFUERZO Y NIVELACIÓN', 3.4),
('BS', 'BÁSICO: CUMPLE SOMERAMENTE CON LOS REQUISITOS, FALTA COMPLEMENTAR, Y DESARROLLAR DE FORMA OPORTUNA LOS RECURSOS EFECTIVOS Y CONCERTAR EL DOMINIO DEL CONOCIMIENTO. REQUIERE ACCIONES PREVENTIVAS Y CORRECTIVAS.', 'POR ALCANZAR', ' ALCANZA LOS LOGROS Y DESEMPEÑOS MÍNIMOS EN CADA UNO DE LOS PENSAMIENTOS ESTABLECIDOS EN EL PEI. DESARROLLA UN MÍNIMO DE ACTIVIDADES CURRICULARES REQUERIDAS.', 3.9),
('A', 'ALTO: CUMPLE SATISFACTORIAMENTE CON EL REQUISITO, DEMUESTRA EMPEÑO, CONSTANCIA Y DEDICACIÓN, HACE USO DE LOS RECURSOS Y COMPRENDE CRITERIOS DE CONOCIMIENTO REQUIERE ACCIONES DE MEJORA.', 'ALCANZADO POR MEJORAR', ' ALCANZA TODOS LOS LOGROS PROPUESTO EN CADA UNO DE LOS PENSAMIENTOS ESTABLECIDOS EN EL PEI. RECONOCE Y SUPERA ALGUNAS FALENCIAS O DIFICULTADES QUE PUEDA PRESENTAR DURANTE SU PROCESO FORMATIVO.', 4.6),
('S', 'SUPERIOR: CUMPLE A CABALIDAD CON EL REQUISITO, ES ASERTIVO, DILIGENTE, OPORTUNO Y HACE USO EFECTIVO DE LOS RECURSOS, SE DESTACA Y ES PROPOSITIVO REQUIERE ACCIONES DE EXALTACIÓN.', 'ALCANZADO', ' ALCANZA TODOS LOS DESEMPEÑOS Y LOGROS PROPUESTOS EN CADA UNO DE LOS PENSAMIENTOS ESTABLECIDOS EN EL PEI. LOGRA DESTACARSE UN CADA UNO DE LOS PENSAMIENTOS POR SU CAPACIDAD DE ANÁLISIS Y REFLEXIÓN EN LAS DIFERENTES TEMÁTICAS DESARROLLADAS.', 5.0)
;